### ISSUE TITLE
Request for Direct Download Link of Pre-trained Model Parameters

### ISSUE THREAD

**Issue by ZhengyaoFang** [bytedance/oclip#9]
Hello! I would like to visualize the attention map using [the pre-trained model](https://entuedu-my.sharepoint.com/:u:/r/personal/xuec0003_e_ntu_edu_sg/Documents/opensource/oCLIP/Pre-trained%20Models/RN50_synthtext.pt?csf=1&web=1&e=uVnGWs) parameters you provided. However, the SharePoint link you provided does not allow for a direct download of the model parameters. Could you please provide a download link on OneDrive or another platform? I would greatly appreciate it!

**Comment by YaohouF** [comment]
Hi, @ZhengyaoFang. Wonder if you got the pre-trained model? It will be appreciated if you can share the download link.
